{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "be-springboot.serviceAccountName" . }}
  labels:
    {{- include "be-springboot.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    iam.gke.io/gcp-service-account: {{ include "be-springboot.serviceAccountName" . }}-gsa@ dev-001 .iam.gserviceaccount.com
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
