{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "be-springboot.fullname" . }}
  labels:
    {{- include "be-springboot.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "be-springboot.fullname" . }}
  updatePolicy:
    {{- $mode := "Off" | quote -}}
    {{ if .Values.vpa.updateMode }}
    {{- $mode = .Values.vpa.updateMode | quote -}}
    {{ end}}
    updateMode: {{ $mode }}
  resourcePolicy:
    containerPolicies: []
{{- end }}
